# Generated by Django 3.0 on 2019-12-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='post_date',
            new_name='date_created',
        ),
    ]
